import {chromium} from '../../Editor/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const assets=path.resolve('Android/app/src/main/assets/reader');
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:1,isMobile:true,hasTouch:true});
await context.addInitScript(()=>{window.__requests=[];window.AndroidBridge={postMessage(value){window.__requests.push(JSON.parse(value));}};});
await context.route('**/*',async route=>{
 const url=new URL(route.request().url());
 if(url.hostname!=='appassets.androidplatform.net') return route.abort();
 if(url.pathname.startsWith('/media/'))return route.fulfill({status:404,body:''});
 const rel=url.pathname.replace(/^\/reader\//,'');
 try{const data=await fs.readFile(path.join(assets,rel));const ext=path.extname(rel);await route.fulfill({body:data,contentType:({'.html':'text/html','.js':'application/javascript','.css':'text/css','.woff2':'font/woff2','.woff':'font/woff','.ttf':'font/ttf'})[ext]||'application/octet-stream'});}catch{await route.fulfill({status:404,body:''});}
});
const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto('https://appassets.androidplatform.net/reader/index.html');await page.waitForFunction(()=>window.ReaderHost);
await fs.mkdir('Android/test-results',{recursive:true});await page.screenshot({path:'Android/test-results/phone-welcome.png'});
	const original='---\ntitle: Android 읽기\n---\n\n[TOC]\n\n# 오늘의 기록\n\n읽는 것에 집중하는 나만의 공간입니다. **원본은 그대로** 보존합니다.\n\n## 문서 둘러보기\n\n- 첫 번째 문장\n- 두 번째 문장\n- [x] 완료한 기록\n- [ ] 이어서 읽을 기록\n\n참조 문장[^1]과 [링크][ref]입니다.\n\n[^1]: 각주 내용은 읽기 전용으로 표시합니다.\n\n[ref]: https://example.invalid/reference\n\n> 작은 기록이 모여 하나의 이야기가 됩니다.\n\n| 항목 | 내용 |\n| --- | --- |\n| 파일 | 읽기 전용 |\n| 테마 | 다크 · 라이트 · 나이트 |\n\n```js\nconsole.log("hello");\n```\n\n수식 $x^2$ 입니다.\n\n$$\na^2+b^2=c^2\n$$\n\n```mermaid\ngraph LR\n A[파일] --> B[읽기]\n```\n\n![외부 그림](https://example.invalid/picture.png)\n\n<script>window.BAD=true</script>\n';
await page.evaluate(text=>window.ReaderHost.receive({type:'document',id:'test-session',name:'오늘의 기록.md',text,hasFolder:true}),original);
await page.waitForFunction(()=>window.ReaderHost.snapshot().ready==='test-session');await page.locator('.diagram-block svg').waitFor();
const diagramBeforeClick=await page.locator('.diagram-block svg').innerHTML();
await page.locator('.diagram-block svg').tap({position:{x:20,y:20}});
assert.equal(await page.locator('.diagram-block svg').innerHTML(),diagramBeforeClick);
const codeBlock=page.locator('#document pre code').filter({hasText:'console.log'});
const codeBeforeClick=await codeBlock.innerHTML();await codeBlock.tap();
assert.equal(await codeBlock.innerHTML(),codeBeforeClick);
assert.equal(await page.locator('#document input,#document textarea,#document [contenteditable=true]').count(),0);
assert.equal(await page.locator('.task-checkbox').count(),2);assert.equal(await page.locator('.task-checkbox button').count(),0);assert.equal(await page.evaluate(()=>window.BAD),undefined);
assert.equal((await page.locator('.front-matter pre').textContent()).trimEnd(),'---\ntitle: Android 읽기\n---');assert.match(await page.locator('#document').innerText(),/각주 내용/);
assert.equal(await page.locator('.footnote-ref').count(),1);assert.equal(await page.locator('.footnotes').count(),1);assert.equal(await page.locator('.footnote-ref a').getAttribute('href'),'#fn1');assert.equal(await page.locator('.footnote-backref').getAttribute('href'),'#fnref1');
assert.equal(await page.locator('.footnote-backref').evaluateAll(links=>links.every(link=>{const id=decodeURIComponent(link.getAttribute('href').slice(1));return document.getElementById(id)!==null;})),true);
assert.doesNotMatch(await page.locator('#document').innerText(),/\[\^1\]|\[ref\]/);
assert.equal(await page.locator('a[href="https://example.invalid/reference"]').textContent(),'링크');
const tocLink=page.locator('.table-of-contents a[data-jump]').filter({hasText:'문서 둘러보기'});assert.equal(await tocLink.count(),1);assert.equal(decodeURIComponent(await tocLink.getAttribute('href')),'#문서-둘러보기');await tocLink.click();assert.equal(await page.locator('#문서-둘러보기').count(),1);
assert.equal(await page.locator('#document img[src^="https://example.invalid"]').count(),0);assert.ok(await page.locator('.katex').count()>=2);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=screen.width),true);
await page.screenshot({path:'Android/test-results/phone-reading-night-default.png'});
await page.getByRole('button',{name:'파일과 목차',exact:true}).click();await page.getByRole('tab',{name:'목차',exact:true}).click();assert.equal(await page.locator('#outline button').filter({hasText:'Android 읽기'}).count(),0);await page.locator('#outline button').filter({hasText:'문서 둘러보기'}).click();assert.equal(await page.locator('#sidebar').evaluate(n=>n.inert),true);
await page.getByRole('button',{name:'본문 검색',exact:true}).click();await page.locator('#query').fill('기록');await page.waitForFunction(()=>document.querySelectorAll('mark.reader-match').length>0);assert.match(await page.locator('#match-count').innerText(),/1 \/ /);await page.getByRole('button',{name:'다음 결과',exact:true}).click();assert.match(await page.locator('#match-count').innerText(),/2 \/ /);await page.getByRole('button',{name:'검색 닫기',exact:true}).click();
await page.getByRole('button',{name:'읽기 설정',exact:true}).click();await page.getByRole('button',{name:'라이트',exact:true}).click();await page.waitForFunction(()=>window.ReaderHost.snapshot().theme==='light');await page.locator('#settings .primary').click();
await page.waitForFunction(()=>document.querySelector('#loading').hidden);await page.screenshot({path:'Android/test-results/phone-reading-light.png'});
await page.locator('[data-remote-images]').click();assert.equal(await page.evaluate(()=>window.__requests.at(-1).type),'allowRemote');assert.equal(await page.evaluate(()=>window.ReaderHost.snapshot().remoteAllowed),false);
await page.evaluate(()=>window.ReaderHost.receive({type:'remoteAllowed',id:'wrong-session'}));assert.equal(await page.evaluate(()=>window.ReaderHost.snapshot().remoteAllowed),false);
await page.evaluate(()=>window.ReaderHost.receive({type:'remoteAllowed',id:'test-session'}));await page.waitForFunction(()=>window.ReaderHost.snapshot().remoteAllowed);
await page.evaluate(()=>window.ReaderHost.receive({type:'document',id:'second',name:'다음.md',text:'# 다음 문서\n\n![외부](https://example.invalid/a.png)',hasFolder:false}));await page.waitForFunction(()=>window.ReaderHost.snapshot().ready==='second');assert.equal(await page.evaluate(()=>window.ReaderHost.snapshot().remoteAllowed),false);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.setViewportSize({width:1024,height:768});await page.evaluate(()=>window.ReaderHost.receive({type:'document',id:'tablet',name:'오늘의 기록.md',text:'# 태블릿 읽기\n\n넓은 화면에서도 편하게 읽습니다.\n\n## 목차\n\n본문입니다.',hasFolder:true}));await page.waitForFunction(()=>window.ReaderHost.snapshot().ready==='tablet');await page.screenshot({path:'Android/test-results/tablet-reading.png'});
assert.deepEqual(errors,[]);
console.log(JSON.stringify({passed:true,checks:['phone welcome and reading','no writable document elements','display-only tasks','HTML disabled','Front Matter and TOC navigation','resolved reference links','footnote references and back-navigation','metadata excluded from outline','tables code math Mermaid','outline navigation','search next result','theme changes','remote opt-in and stale-session denial','remote approval resets per document','phone horizontal fit','tablet layout','no renderer exceptions']},null,2));
await browser.close();
