import { _electron as electron } from '../../Editor/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const data=await fs.mkdtemp(path.join(os.tmpdir(),'mymarkdown-ui-'));
const workspace=path.join(data,'문서 작업 폴더');await fs.mkdir(workspace);
await fs.writeFile(path.join(workspace,'기존 문서.md'),'# 기존 문서\n\n검토할 내용\n');
await fs.mkdir(path.join(workspace,'이동할 폴더'));
const app=await electron.launch({executablePath:path.resolve('Windows/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'),args:[path.resolve('Windows'),'--qa-data',data]});
try{
 const page=await app.firstWindow();page.setDefaultTimeout(15000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const frame=page.frame({url:'app://editor/index.html'})||await page.waitForEvent('framenavigated',{predicate:f=>f.url()==='app://editor/index.html'});
 await frame.waitForFunction(()=>window.MarkdownHost?.snapshot);
 await app.evaluate(async(_,folder)=>globalThis.__qa.grant(folder),workspace);
 await page.getByLabel('파일 관리',{exact:true}).click();
 await page.locator('[data-file-action="createFile"]').click();
 await page.locator('#item-input').fill('기존 문서.md');await page.locator('#item-input').press('Enter');
 await page.locator('#item-error:not([hidden])').waitFor();
 assert.equal(await page.locator('#item-dialog').evaluate(d=>d.open),true);
 await page.locator('#item-input').fill('화면에서 생성한 문서.md');await page.locator('#item-input').press('Enter');
 await page.locator('#item-dialog').waitFor({state:'hidden'});
 await frame.waitForFunction(()=>window.MarkdownHost.snapshot().documentID.endsWith('화면에서 생성한 문서.md'));
 await frame.evaluate(()=>window.MarkdownHost.receive({type:'insert',...window.MarkdownHost.snapshot(),text:'# Windows 문서 공간\n\n**편집한 내용**을 원래 위치에 저장합니다.\n\n- 문서와 폴더 관리\n- 검색 결과 검토 후 바꾸기\n'}));
 await page.waitForTimeout(200);await page.evaluate(()=>window.desktop.invoke('save'));
 await page.getByLabel('파일 관리',{exact:true}).click();
 await page.locator('[data-file-action="rename"]').click();
 await page.locator('#item-input').fill('이름을 바꾼 문서.md');await page.locator('#item-input').press('Enter');
 await page.locator('#item-dialog').waitFor({state:'hidden'});
 await frame.waitForFunction(()=>window.MarkdownHost.snapshot().documentID.endsWith('이름을 바꾼 문서.md'));
 await page.getByLabel('파일 관리',{exact:true}).click();
 await page.locator('[data-file-action="move"]').click();
 await page.locator('#item-dialog select').selectOption(path.join(workspace,'이동할 폴더'));
 await page.locator('#item-dialog button[type="submit"]').click();await page.locator('#item-dialog').waitFor({state:'hidden'});
 await frame.waitForFunction(()=>window.MarkdownHost.snapshot().documentID.includes('이동할 폴더'));
 assert.equal(await page.locator('#tree [aria-selected="true"]').innerText(), '이름을 바꾼 문서.md');
 await page.locator('[data-tab="search"]').click();await page.locator('#search-query').fill('검토할');await page.locator('#search-query').press('Enter');
 await page.locator('[aria-label="바꿀 내용"]').fill('확인한');await page.getByRole('button',{name:'바꾸기 검토',exact:true}).click();
 await page.locator('#replace-dialog').waitFor();
 await fs.mkdir('Windows/test-results',{recursive:true});await page.screenshot({path:'Windows/test-results/replace-review.png'});
 await page.locator('#apply-replace').click();await page.waitForFunction(()=>document.querySelector('#apply-replace').textContent==='닫기');
 assert.equal(await page.locator('#replace-files input').count(),0);assert.ok((await page.locator('#replace-outcomes').innerText()).includes('저장됨'));
 assert.ok((await fs.readFile(path.join(workspace,'기존 문서.md'),'utf8')).includes('확인한'));
 await page.screenshot({path:'Windows/test-results/replace-outcome.png'});await page.locator('#apply-replace').click();
 await page.locator('[data-tab="files"]').click();
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(800,560));
 await page.waitForTimeout(200);await page.screenshot({path:'Windows/test-results/electron-narrow.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const footer=await page.locator('.statusbar').boundingBox();assert.ok(footer.y+footer.height<=560);
 await page.locator('[data-action="settings"]').click();await page.screenshot({path:'Windows/test-results/settings-narrow.png'});
 const apply=await page.locator('#save-settings').boundingBox();assert.ok(apply.y+apply.height<560);
 const settings=await page.locator('#settings-dialog').boundingBox();assert.ok(settings.x>=0 && settings.x+settings.width<=800);assert.ok(settings.y>=0 && settings.y+settings.height<=560);
 await page.keyboard.press('Escape');assert.equal(await page.locator('#settings-dialog').evaluate(d=>d.open),false);
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,checks:['create dialog + duplicate error retention','rename through UI','move folder picker','active document visible','review before/after','result replaces preview','800x560 layout','settings keyboard escape','no renderer exceptions']},null,2));
}finally{await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{});}
